### ISSUE TITLE
Using mpesa openapi

### ISSUE THREAD

**Issue by alphaolomi** [MuhammadAnas786/mpesa-openapi#1]
hello @MuhammadAnas786 

any feedback working on mpesa openapi

**Comment by MuhammadAnas786** [comment]
It's still in development... cant say much, will let you know when i'm done..

**Comment by alphaolomi** [comment]
Oh great! Reach out in case of any issue, looking forward to you feedback

**Comment by MuhammadAnas786** [comment]
Yeah, definitely.

**Comment by alphaolomi** [comment]
Hi @MuhammadAnas786 how is it going

**Comment by MuhammadAnas786** [comment]
yea, its great. Its in production almost.
